Repository ISIS3510-S2-G23/swift_project, pull requests merged in 2025-03, with the labels that each got.

#8 Include Points View Basic Structure
  swift_app/swift_app/Assets.xcassets/AppBlue.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/AppGreenGreen.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/AppGreenLight.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/AppGreenYellow.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/EcoChooseBlue.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/EcoLightPurple.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/EcoMainPurple.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/EcoSecondaryPurple.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/Person8.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/Person8.imageset/person8 1.png
  swift_app/swift_app/Assets.xcassets/Person8.imageset/person8 2.png
  swift_app/swift_app/Assets.xcassets/Person8.imageset/person8.png
  swift_app/swift_app/Points/Views/PointsView.swift
Labels: code

#9 Update .gitignore to include new folder
  .gitignore
Labels: code

#10 Update Develop to it is the same as base main branch
  .gitignore
  swift_app/swift_app/Assets.xcassets/AppBlue.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/AppGreenGreen.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/AppGreenLight.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/AppGreenYellow.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/EcoChooseBlue.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/EcoLightPurple.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/EcoMainPurple.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/EcoSecondaryPurple.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/Person8.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/Person8.imageset/person8 1.png
  swift_app/swift_app/Assets.xcassets/Person8.imageset/person8 2.png
  swift_app/swift_app/Assets.xcassets/Person8.imageset/person8.png
  swift_app/swift_app/Points/Views/PointsView.swift
Labels: code

#11 Branch for Auth
  .gitignore
  swift_app/swift_app.xcodeproj/project.pbxproj
  swift_app/swift_app.xcodeproj/project.xcworkspace/xcuserdata/paulinaarrazola.xcuserdatad/UserInterfaceState.xcuserstate
  swift_app/swift_app/Assets.xcassets/Figure 1.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/Figure 1.imageset/Figure 1.png
  swift_app/swift_app/Assets.xcassets/Google logo.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/Google logo.imageset/Screenshot 2025-03-12 at 3.16.46 PM.png
  swift_app/swift_app/Assets.xcassets/Login Button.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/Login Button.imageset/Screenshot 2025-03-12 at 11.53.24 AM.png
  swift_app/swift_app/Assets.xcassets/Long Login.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/Long Login.imageset/Screenshot 2025-03-12 at 11.59.53 AM.png
  swift_app/swift_app/Assets.xcassets/Long SignUp.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/Long SignUp.imageset/Screenshot 2025-03-12 at 3.02.52 PM.png
  swift_app/swift_app/Assets.xcassets/Sign Up Button.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/Sign Up Button.imageset/Screenshot 2025-03-12 at 11.54.11 AM.png
  swift_app/swift_app/Authentication/Services/AuthService.swift
  swift_app/swift_app/Authentication/Views/LogInView.swift
  swift_app/swift_app/Authentication/Views/OptionsView.swift
  swift_app/swift_app/Authentication/Views/SignUpView.swift
  swift_app/swift_app/GoogleService-Info.plist
Labels: code

#12 Merge main to develop
  .gitignore
  swift_app/swift_app.xcodeproj/project.pbxproj
  swift_app/swift_app.xcodeproj/project.xcworkspace/xcuserdata/paulinaarrazola.xcuserdatad/UserInterfaceState.xcuserstate
  swift_app/swift_app/Assets.xcassets/Figure 1.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/Figure 1.imageset/Figure 1.png
  swift_app/swift_app/Assets.xcassets/Google logo.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/Google logo.imageset/Screenshot 2025-03-12 at 3.16.46 PM.png
  swift_app/swift_app/Assets.xcassets/Login Button.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/Login Button.imageset/Screenshot 2025-03-12 at 11.53.24 AM.png
  swift_app/swift_app/Assets.xcassets/Long Login.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/Long Login.imageset/Screenshot 2025-03-12 at 11.59.53 AM.png
  swift_app/swift_app/Assets.xcassets/Long SignUp.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/Long SignUp.imageset/Screenshot 2025-03-12 at 3.02.52 PM.png
  swift_app/swift_app/Assets.xcassets/Sign Up Button.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/Sign Up Button.imageset/Screenshot 2025-03-12 at 11.54.11 AM.png
  swift_app/swift_app/Authentication/Services/AuthService.swift
  swift_app/swift_app/Authentication/Views/LogInView.swift
  swift_app/swift_app/Authentication/Views/OptionsView.swift
  swift_app/swift_app/Authentication/Views/SignUpView.swift
  swift_app/swift_app/GoogleService-Info.plist
Labels: code

#18 Navigation between the different log in and sign up options
  .gitignore
  swift_app/swift_app.xcodeproj/project.pbxproj
  swift_app/swift_app.xcodeproj/project.xcworkspace/xcuserdata/paulinaarrazola.xcuserdatad/UserInterfaceState.xcuserstate
  swift_app/swift_app/Authentication/Views/LogInView.swift
  swift_app/swift_app/Authentication/Views/OptionsView.swift
  swift_app/swift_app/Authentication/Views/SignUpView.swift
  swift_app/swift_app/swift_appApp.swift
Labels: code

#20 Advancements in Points View and Sub Views
  swift_app/swift_app/Assets.xcassets/CompleteChallenge.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/CompleteChallenge.imageset/icon.png
  swift_app/swift_app/Assets.xcassets/CompletedButtonGreen.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/CompletedGreen.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/IncompleteChallenge.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/IncompleteChallenge.imageset/icon (1).png
  swift_app/swift_app/Assets.xcassets/IncompletedDonut.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/IncompletedDonut.imageset/donut_large.png
  swift_app/swift_app/Points/Challenges and Rewards/Challenge.swift
  swift_app/swift_app/Points/Challenges and Rewards/ChallengeCardView.swift
  swift_app/swift_app/Points/Challenges and Rewards/ChallengePopUpView.swift
  swift_app/swift_app/Points/Challenges and Rewards/ChallengesView.swift
  swift_app/swift_app/Points/Challenges and Rewards/ChallengesViewModel.swift
  swift_app/swift_app/Points/Challenges and Rewards/RewardCardView.swift
  swift_app/swift_app/Points/Challenges and Rewards/RewardsView.swift
  swift_app/swift_app/Points/Near Me/MapVIewController.swift
  swift_app/swift_app/Points/Near Me/NearMeView.swift
  swift_app/swift_app/Points/Views/PointsView.swift
Labels: code

#26 Integrate auth in log in
  .gitignore
  swift_app/swift_app.xcodeproj/project.xcworkspace/xcuserdata/paulinaarrazola.xcuserdatad/UserInterfaceState.xcuserstate
  swift_app/swift_app/Authentication/Services/AuthService.swift
  swift_app/swift_app/Authentication/Services/AuthenticationService.swift
  swift_app/swift_app/Authentication/Views/LogInView.swift
  swift_app/swift_app/swift_appApp.swift
Labels: enhancement

#29 Functional PopUps for Challenges and Rewards
  swift_app/swift_app/Points/Challenges and Rewards/Challenge.swift
  swift_app/swift_app/Points/Challenges and Rewards/ChallengeCardView.swift
  swift_app/swift_app/Points/Challenges and Rewards/ChallengesView.swift
  swift_app/swift_app/Points/Challenges and Rewards/ChallengesViewModel.swift
  swift_app/swift_app/Points/Challenges and Rewards/ImagePicker.swift
  swift_app/swift_app/Points/Challenges and Rewards/RegisterVisitPopUpView.swift
  swift_app/swift_app/Points/Challenges and Rewards/RewardCardView.swift
  swift_app/swift_app/Points/Challenges and Rewards/RewardPopUpView.swift
  swift_app/swift_app/Points/Challenges and Rewards/RewardsView.swift
  swift_app/swift_app/Points/Views/PointsView.swift
Labels: code

#30 Connected Map with FB DB
  swift_app/swift_app/Points/Near Me/MapVIewController.swift
Labels: code

#33 Connected Challenge/Rewards with the data base
  swift_app/swift_app/Points/Challenges and Rewards/Challenge.swift
  swift_app/swift_app/Points/Challenges and Rewards/ChallengesView.swift
  swift_app/swift_app/Points/Challenges and Rewards/ChallengesViewModel.swift
  swift_app/swift_app/Points/Challenges and Rewards/RegisterVisitPopUpView.swift
  swift_app/swift_app/Points/Challenges and Rewards/UserChallenge.swift
  swift_app/swift_app/Points/Near Me/MapVIewController.swift
  swift_app/swift_app/Points/Near Me/NearMeView.swift
  swift_app/swift_app/Tab Bar/MainTabBar.swift
Labels: code

#35 Successful connection to the camera
  .gitignore
  swift_app/swift_app.xcodeproj/project.pbxproj
  swift_app/swift_app.xcodeproj/project.xcworkspace/xcuserdata/paulinaarrazola.xcuserdatad/UserInterfaceState.xcuserstate
Labels: duplicate, enhancement

#37 Map now opens in users location
  .gitignore
  swift_app/swift-app-Info.plist
  swift_app/swift_app.xcodeproj/project.pbxproj
  swift_app/swift_app.xcodeproj/project.xcworkspace/xcuserdata/paulinaarrazola.xcuserdatad/UserInterfaceState.xcuserstate
  swift_app/swift_app/Points/Near Me/MapVIewController.swift
Labels: bug

#39 Final Merge Into Main
  .gitignore
  swift_app/swift-app-Info.plist
  swift_app/swift_app.xcodeproj/project.pbxproj
  swift_app/swift_app.xcodeproj/project.xcworkspace/xcuserdata/paulinaarrazola.xcuserdatad/UserInterfaceState.xcuserstate
  swift_app/swift_app/Account/AccountView.swift
  swift_app/swift_app/Add Post/AddPostView.swift
  swift_app/swift_app/Assets.xcassets/ArrowButton.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/ArrowButton.imageset/Image.png
  swift_app/swift_app/Assets.xcassets/CompleteChallenge.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/CompleteChallenge.imageset/icon.png
  swift_app/swift_app/Assets.xcassets/CompletedButtonGreen.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/CompletedGreen.colorset/Contents.json
  swift_app/swift_app/Assets.xcassets/Farmer.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/Farmer.imageset/Image.png
  swift_app/swift_app/Assets.xcassets/IncompleteChallenge.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/IncompleteChallenge.imageset/icon (1).png
  swift_app/swift_app/Assets.xcassets/IncompletedDonut.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/IncompletedDonut.imageset/donut_large.png
  swift_app/swift_app/Assets.xcassets/MenPlant.imageset/Contents.json
  swift_app/swift_app/Assets.xcassets/MenPlant.imageset/Image.png
  swift_app/swift_app/Authentication/Services/AuthService.swift
  swift_app/swift_app/Authentication/Services/AuthenticationService.swift
  swift_app/swift_app/Authentication/Views/LogInView.swift
  swift_app/swift_app/Authentication/Views/OptionsView.swift
  swift_app/swift_app/Authentication/Views/SignUpView.swift
  swift_app/swift_app/Home/HomeView.swift
  swift_app/swift_app/Notifications/NotificationsView.swift
  swift_app/swift_app/Points/Challenges and Rewards/Challenge.swift
  swift_app/swift_app/Points/Challenges and Rewards/ChallengeCardView.swift
  swift_app/swift_app/Points/Challenges and Rewards/ChallengePopUpView.swift
  swift_app/swift_app/Points/Challenges and Rewards/ChallengesView.swift
  swift_app/swift_app/Points/Challenges and Rewards/ChallengesViewModel.swift
  swift_app/swift_app/Points/Challenges and Rewards/ImagePicker.swift
  swift_app/swift_app/Points/Challenges and Rewards/RegisterVisitPopUpView.swift
  swift_app/swift_app/Points/Challenges and Rewards/RewardCardView.swift
  swift_app/swift_app/Points/Challenges and Rewards/RewardPopUpView.swift
  swift_app/swift_app/Points/Challenges and Rewards/RewardsView.swift
  swift_app/swift_app/Points/Challenges and Rewards/UserChallenge.swift
  swift_app/swift_app/Points/Near Me/MapViewModel.swift
  swift_app/swift_app/Points/Near Me/NearMeView.swift
  swift_app/swift_app/Points/Views/PointsView.swift
  swift_app/swift_app/Tab Bar/MainTabBar.swift
  swift_app/swift_app/Tab Bar/TabBarView.swift
  swift_app/swift_app/Welcome/WelcomeView1.swift
  swift_app/swift_app/Welcome/WelcomeView2.swift
  swift_app/swift_app/swift_appApp.swift
Labels: code

#40 Bug in sign in corrected
  .gitignore
  swift_app/swift_app.xcodeproj/project.xcworkspace/xcuserdata/paulinaarrazola.xcuserdatad/UserInterfaceState.xcuserstate
  swift_app/swift_app/Authentication/Views/SignUpView.swift
Labels: bug
